# Copyright (c) YugaByte, Inc.

baseurl = "http://docs.yugabyte.com"
languageCode = "en-us"
title = "YugaByte Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-104956980-1"

[params]
	# General information
	author = "Team YugaByte"
	description = "YugaByte Product Documentation"
	copyright = "YugaByte Inc."
	block_indexing = true

	version = "Beta"
	logo = "/images/logo.png"
	favicon = "/images/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = "stylesheets/highlight/dracula.css"

	[params.palette]
    	primary = "orange"
    	accent  = "amber"

    [params.font]
    	text = "Open Sans"
    	code = "Inconsolata"

[social]
	# github = "YugaByte"
	# twitter = "YugaByte"
	email   = "support@yugabyte.com"

[[menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 1


[[menu.main]]
	name   = "FAQs"
	url    = "faq/"
	weight = 2

[[menu.main]]
	name = "Community Edition"
	identifier = "community-edition"
	weight = 3

[[menu.main]]
	name = "Quick Start"
	identifier = "community-quick-start"
	parent = "community-edition"
	url = "community-edition/quick-start/"
	weight = 5

[[menu.main]]
	name   = "Develop"
	parent = "community-edition"
	url    = "community-edition/develop/"
	weight = 10

[[menu.main]]
	name   = "Deploy"
	parent = "community-edition"
	url    = "community-edition/deploy/"
	weight = 20

[[menu.main]]
	name = "Enterprise Edition"
	identifier = "enterprise-edition"
	weight = 40

[[menu.main]]
	name = "Deploy Admin Console"
	parent = "enterprise-edition"
	url = "enterprise-edition/deploy/"
	weight = 50

[[menu.main]]
	name   = "Administer"
	parent = "enterprise-edition"
	url    = "enterprise-edition/admin/"
	weight = 60

[[menu.main]]
	name   = "Architecture"
	identifier = "architecture"
	weight = 70

[[menu.main]]
	name   = "Concepts"
	parent = "architecture"
	url = "architecture/concepts/"
	weight = 80

[[menu.main]]
	name   = "Core Functions"
	parent = "architecture"
	url = "architecture/core-functions/"
	weight = 90

#[[menu.main]]
#	name   = "Operations"
#	parent = "architecture"
#	url = "architecture/operations/"
#	weight = 95

#[[menu.main]]
#	name   = "Enterprise Features"
#	parent = "architecture"
#	url = "architecture/enterprise-features/"
#	weight = 100

[[menu.main]]
	name   = "Comparisons"
	parent = "architecture"
	url = "architecture/comparisons/"
	weight = 110


[[menu.main]]
	name   = "Client API Reference"
	weight = 120
	identifier = "API"

[[menu.main]]
	name = "Apache Cassandra"
	weight = 130
	identifier = "api-cql"
	parent = "API"
	url = "api/cql/"

[[menu.main]]
	name = "Redis"
	weight = 140
	identifier = "api-redis"
	parent = "API"
	url = "api/redis/"

[[menu.main]]
	name = "APPEND"
	weight = 140
	identifier = "api-redis-append"
	parent = "api-redis"
	url = "api/redis/append/"

[[menu.main]]
	name   = "Admin Reference"
	weight = 150
	identifier = "admin"

[[menu.main]]
	name = "yb-ctl"
	weight = 160
	identifier = "yb-ctl"
	parent = "admin"
	url = "admin/yb-ctl/"

[[menu.main]]
	name = "yb-master"
	weight = 170
	identifier = "yb-master"
	parent = "admin"
	url = "admin/yb-master/"

[[menu.main]]
	name = "yb-tserver"
	weight = 180
	identifier = "yb-tserver"
	parent = "admin"
	url = "admin/yb-tserver/"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
