# Copyright (c) YugaByte, Inc.

baseurl = "https://www.yugabyte.com/docs"
languageCode = "en-us"
title = "YugaByte Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Team YugaByte"
	description = "YugaByte Product Documentation"
	# copyright = "Released under the MIT license"
	block_indexing = true

	version = "early release"
	logo = "/images/logo.png"
	favicon = "/images/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "orange"
    	accent  = "brown"

    [params.font]
    	text = "Lato"
    	code = "Ubuntu Mono"


[social]
	# twitter = "YugaByte"
	email   = "support@yugabyte.com"


[[menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 1

[[menu.main]]
	name = "Community Edition"
	identifier = "community-edition"
	weight = 2

[[menu.main]]
	name = "Get Started"
	identifier = "community-get-started"
	parent = "community-edition"
	url = "community-edition/get-started/"
	weight = 5

[[menu.main]]
	name   = "Develop"
	parent = "community-edition"
	url    = "community-edition/develop/"
	weight = 10

[[menu.main]]
	name   = "Deploy"
	parent = "community-edition"
	url    = "community-edition/deploy/"
	weight = 20

[[menu.main]]
	name = "Enterprise Edition"
	identifier = "enterprise-edition"
	weight = 30

[[menu.main]]
	name = "Deploy Admin Console"
	identifier = "enterprise-deploy"
	parent = "enterprise-edition"
	url = "enterprise-edition/deploy/"
	weight = 40

[[menu.main]]
	name   = "Administer YugaByte"
	parent = "enterprise-edition"
	url    = "enterprise-edition/admin/"
	weight = 50

[[menu.main]]
	name   = "Learn YugaByte"
	identifier    = "learn"
	weight = 60


[[menu.main]]
	name = "Basics"
	identifier = "learn-basics"
	parent = "learn"
	url = "learn/basics/"
	weight = 65


[[menu.main]]
	name = "Architecture"
	identifier = "learn-architecuture"
	parent = "learn"
	url = "learn/architecture/"
	weight = 70


[[menu.main]]
	name   = "FAQs"
	url    = "faq/"
	weight = 70

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
