---
baseurl: https://docs.yugabyte.com
languageCode: en-us
title: YugaByte DB Docs
metadataformat: yaml
canonifyurls: false
googleAnalytics: UA-104956980-3
algolia:
  index: docs
  appID: 4LBMOWH4F9
params:
  author: Team YugaByte
  description: 'YugaByte DB, a transactional, high performance, planet-scale operational database'
  copyright: 'YugaByte, Inc.'
  block_indexing: false
  version: Beta
  logo: /images/og-image.jpg
  favicon: /images/favicon.ico
  permalink: '#'
  custom_css: []
  custom_js: []
  highlight_css: css/highlight/hemisu.css
  palette:
    primary: orange
    accent: amber
  font:
    text: Open Sans
    code: Inconsolata
social: {}
menu:
  main:
    - name: Introduction
      identifier: intro
blackfriday:
  smartypants: true
  fractions: true
  smartDashes: true
  plainIDAnchors: true
---
