# Copyright (c) YugaByte, Inc.

baseurl = "https://docs.yugabyte.com"
languageCode = "en-us"
title = "YugaByte Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-104956980-1"

[params]
	# General information
	author = "Team YugaByte"
	description = "YugaByte Product Documentation"
	copyright = "YugaByte Inc."
	block_indexing = true

	version = "Beta"
	logo = "/images/logo.png"
	favicon = "/images/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = "stylesheets/highlight/dracula.css"

	[params.palette]
    	primary = "orange"
    	accent  = "amber"

    [params.font]
    	text = "Open Sans"
    	code = "Inconsolata"

[social]
	# github = "YugaByte"
	# twitter = "YugaByte"
	# email   = "support@yugabyte.com"

[[menu.main]]
	name   = "Introduction"
	url    = "introduction/"
	weight = 1

[[menu.main]]
	name   = "FAQs"
	url    = "faq/"
	weight = 2

[[menu.main]]
	name = "Community Edition"
	identifier = "community-edition"
	url = "community-edition/"
	weight = 3

[[menu.main]]
	name = "Quick Start"
	identifier = "community-quick-start"
	parent = "community-edition"
	url = "community-edition/quick-start/"
	weight = 4

[[menu.main]]
	name = "1. Install YugaByte DB"
	parent = "community-quick-start"
	url = "community-edition/quick-start/install/"
	weight = 5

[[menu.main]]
	name = "2. Create Local Cluster"
	parent = "community-quick-start"
	url = "community-edition/quick-start/create-local-cluster/"
	weight = 6

[[menu.main]]
	name = "3. Test YugaByte CQL"
	parent = "community-quick-start"
	url = "community-edition/quick-start/test-yugabyte-cql/"
	weight = 7

[[menu.main]]
	name = "4. Test YugaByte Redis"
	parent = "community-quick-start"
	url = "community-edition/quick-start/test-yugabyte-redis/"
	weight = 8

[[menu.main]]
	name = "Explore Core Features"
	identifier = "community-explore"
	parent = "community-edition"
	url = "community-edition/explore/"
	weight = 9

[[menu.main]]
	name = "Fault Tolerance"
	parent = "community-explore"
	url = "community-edition/explore/fault-tolerance/"
	weight = 10

[[menu.main]]
	name = "Auto Rebalancing"
	parent = "community-explore"
	url = "community-edition/explore/auto-rebalancing/"
	weight = 11

[[menu.main]]
	name   = "Develop Apps"
	parent = "community-edition"
	url    = "community-edition/develop/"
	weight = 12

[[menu.main]]
	name   = "Deploy"
	parent = "community-edition"
	url    = "community-edition/deploy/"
	weight = 20

[[menu.main]]
	name = "Enterprise Edition"
	identifier = "enterprise-edition"
	url = "enterprise-edition/"
	weight = 40

[[menu.main]]
	name = "Deploy Admin Console"
	parent = "enterprise-edition"
	url = "enterprise-edition/deploy/"
	weight = 50

[[menu.main]]
	name   = "Administer"
	parent = "enterprise-edition"
	url    = "enterprise-edition/admin/"
	weight = 60

[[menu.main]]
	name   = "Architecture"
	identifier = "architecture"
	url = "architecture/"
	weight = 70

[[menu.main]]
	name   = "Concepts"
	parent = "architecture"
	url = "architecture/concepts/"
	weight = 80

[[menu.main]]
	name   = "Core Functions"
	parent = "architecture"
	url = "architecture/core-functions/"
	weight = 90

#[[menu.main]]
#	name   = "Operations"
#	parent = "architecture"
#	url = "architecture/operations/"
#	weight = 95

#[[menu.main]]
#	name   = "Enterprise Features"
#	parent = "architecture"
#	url = "architecture/enterprise-features/"
#	weight = 100

[[menu.main]]
	name   = "Comparisons"
	parent = "architecture"
	url = "architecture/comparisons/"
	weight = 110

[[menu.main]]
	name   = "Client API Reference"
	weight = 120
	url = "api/"
	identifier = "API"

[[menu.main]]
	name = "Apache Cassandra"
	weight = 121
	identifier = "api-cql"
	parent = "API"
	url = "api/cql/"

[[menu.main]]
	name = "ALTER TABLE"
	weight = 122
	parent = "api-cql"
	url = "api/cql/ddl_alter_table/"

[[menu.main]]
	name = "CREATE KEYSPACE"
	weight = 123
	parent = "api-cql"
	url = "api/cql/ddl_create_keyspace/"

[[menu.main]]
	name = "CREATE TABLE"
	weight = 124
	parent = "api-cql"
	url = "api/cql/ddl_create_table/"

[[menu.main]]
	name = "CREATE TYPE"
	weight = 125
	parent = "api-cql"
	url = "api/cql/ddl_create_type/"

[[menu.main]]
	name = "DROP KEYSPACE"
	weight = 126
	parent = "api-cql"
	url = "api/cql/ddl_drop_keyspace/"

[[menu.main]]
	name = "DROP TABLE"
	weight = 127
	parent = "api-cql"
	url = "api/cql/ddl_drop_table/"

[[menu.main]]
	name = "DROP TYPE"
	weight = 128
	parent = "api-cql"
	url = "api/cql/ddl_drop_type/"

[[menu.main]]
	name = "USE"
	weight = 129
	parent = "api-cql"
	url = "api/cql/ddl_use/"

[[menu.main]]
	name = "INSERT"
	weight = 130
	parent = "api-cql"
	url = "api/cql/dml_insert/"

[[menu.main]]
	name = "SELECT"
	weight = 131
	parent = "api-cql"
	url = "api/cql/dml_select/"

[[menu.main]]
	name = "UPDATE"
	weight = 132
	parent = "api-cql"
	url = "api/cql/dml_update/"

[[menu.main]]
	name = "DELETE"
	weight = 133
	parent = "api-cql"
	url = "api/cql/dml_delete/"

[[menu.main]]
	name = "Simple Value"
	weight = 134
	parent = "api-cql"
	url = "api/cql/expr_simple/"

[[menu.main]]
	name = "Subscript"
	weight = 135
	parent = "api-cql"
	url = "api/cql/expr_subscript/"

[[menu.main]]
	name = "Operator Call"
	weight = 136
	parent = "api-cql"
	url = "api/cql/expr_ocall/"

[[menu.main]]
	name = "Function Call"
	weight = 137
	parent = "api-cql"
	url = "api/cql/expr_fcall/"

[[menu.main]]
	name = "BIGINT"
	weight = 138
	parent = "api-cql"
	url = "api/cql/type_int/"

[[menu.main]]
	name = "BLOB"
	weight = 139
	parent = "api-cql"
	url = "api/cql/type_blob/"

[[menu.main]]
	name = "BOOLEAN"
	weight = 140
	parent = "api-cql"
	url = "api/cql/type_bool/"

[[menu.main]]
	name = "COUNTER"
	weight = 141
	parent = "api-cql"
	url = "api/cql/type_int/"

[[menu.main]]
	name = "DECIMAL"
	weight = 142
	parent = "api-cql"
	url = "api/cql/type_number/"

[[menu.main]]
	name = "DOUBLE"
	weight = 143
	parent = "api-cql"
	url = "api/cql/type_number/"

[[menu.main]]
	name = "FLOAT"
	weight = 144
	parent = "api-cql"
	url = "api/cql/type_number/"

[[menu.main]]
	name = "FROZEN"
	weight = 145
	parent = "api-cql"
	url = "api/cql/type_frozen/"

[[menu.main]]
	name = "INET"
	weight = 146
	parent = "api-cql"
	url = "api/cql/type_inet/"

[[menu.main]]
	name = "INT"
	weight = 147
	parent = "api-cql"
	url = "api/cql/type_int/"

[[menu.main]]
	name = "LIST"
	weight = 148
	parent = "api-cql"
	url = "api/cql/type_collection/"

[[menu.main]]
	name = "MAP"
	weight = 149
	parent = "api-cql"
	url = "api/cql/type_collection/"

[[menu.main]]
	name = "SET"
	weight = 150
	parent = "api-cql"
	url = "api/cql/type_collection/"

[[menu.main]]
	name = "SMALLINT"
	weight = 151
	parent = "api-cql"
	url = "api/cql/type_int/"

[[menu.main]]
	name = "TEXT"
	weight = 152
	parent = "api-cql"
	url = "api/cql/type_text/"

[[menu.main]]
	name = "TIMESTAMP"
	weight = 153
	parent = "api-cql"
	url = "api/cql/type_timestamp/"

[[menu.main]]
	name = "TIMEUUID"
	weight = 154
	parent = "api-cql"
	url = "api/cql/type_uuid/"

[[menu.main]]
	name = "TINYINT"
	weight = 155
	parent = "api-cql"
	url = "api/cql/type_int/"

[[menu.main]]
	name = "UUID"
	weight = 156
	parent = "api-cql"
	url = "api/cql/type_uuid/"

[[menu.main]]
	name = "Redis"
	weight = 200
	identifier = "api-redis"
	parent = "API"
	url = "api/redis/"

[[menu.main]]
	name = "APPEND"
	weight = 201
	parent = "api-redis"
	url = "api/redis/append/"

[[menu.main]]
	name = "AUTH"
	weight = 202
	parent = "api-redis"
	url = "api/redis/auth/"

[[menu.main]]
	name = "CONFIG"
	weight = 203
	parent = "api-redis"
	url = "api/redis/config/"

[[menu.main]]
	name = "DEL"
	weight = 204
	parent = "api-redis"
	url = "api/redis/del/"

[[menu.main]]
	name = "ECHO"
	weight = 205
	parent = "api-redis"
	url = "api/redis/echo/"

[[menu.main]]
	name = "EXISTS"
	weight = 206
	parent = "api-redis"
	url = "api/redis/exists/"

[[menu.main]]
	name = "GET"
	weight = 207
	parent = "api-redis"
	url = "api/redis/get/"

[[menu.main]]
	name = "GETRANGE"
	weight = 208
	parent = "api-redis"
	url = "api/redis/getrange/"

[[menu.main]]
	name = "GETSET"
	weight = 209
	parent = "api-redis"
	url = "api/redis/getset/"

[[menu.main]]
	name = "HDEL"
	weight = 210
	parent = "api-redis"
	url = "api/redis/hdel/"

[[menu.main]]
	name = "HEXISTS"
	weight = 211
	parent = "api-redis"
	url = "api/redis/hexists/"

[[menu.main]]
	name = "HGET"
	weight = 212
	parent = "api-redis"
	url = "api/redis/hget/"

[[menu.main]]
	name = "HGETALL"
	weight = 213
	parent = "api-redis"
	url = "api/redis/hgetall/"

[[menu.main]]
	name = "HKEYS"
	weight = 214
	parent = "api-redis"
	url = "api/redis/hkeys/"

[[menu.main]]
	name = "HLEN"
	weight = 215
	parent = "api-redis"
	url = "api/redis/hlen/"

[[menu.main]]
	name = "HMGET"
	weight = 216
	parent = "api-redis"
	url = "api/redis/hmget/"

[[menu.main]]
	name = "HMSET"
	weight = 217
	parent = "api-redis"
	url = "api/redis/hmset/"

[[menu.main]]
	name = "HSET"
	weight = 218
	parent = "api-redis"
	url = "api/redis/hmet/"

[[menu.main]]
	name = "HSTRLEN"
	weight = 219
	parent = "api-redis"
	url = "api/redis/hstrlen/"

[[menu.main]]
	name = "HVALS"
	weight = 220
	parent = "api-redis"
	url = "api/redis/hvals/"

[[menu.main]]
	name = "INCR"
	weight = 221
	parent = "api-redis"
	url = "api/redis/incr/"

[[menu.main]]
	name = "MGET"
	weight = 222
	parent = "api-redis"
	url = "api/redis/mget/"

[[menu.main]]
	name = "MSET"
	weight = 223
	parent = "api-redis"
	url = "api/redis/mset/"

[[menu.main]]
	name = "ROLE"
	weight = 224
	parent = "api-redis"
	url = "api/redis/role/"

[[menu.main]]
	name = "SADD"
	weight = 225
	parent = "api-redis"
	url = "api/redis/sadd/"

[[menu.main]]
	name = "SCARD"
	weight = 226
	parent = "api-redis"
	url = "api/redis/scard/"

[[menu.main]]
	name = "SET"
	weight = 227
	parent = "api-redis"
	url = "api/redis/set/"

[[menu.main]]
	name = "SETRANGE"
	weight = 228
	parent = "api-redis"
	url = "api/redis/setrange/"

[[menu.main]]
	name = "SISMEMBER"
	weight = 229
	parent = "api-redis"
	url = "api/redis/sismember/"

[[menu.main]]
	name = "SMEMBERS"
	weight = 230
	parent = "api-redis"
	url = "api/redis/smembers/"

[[menu.main]]
	name = "SREM"
	weight = 231
	parent = "api-redis"
	url = "api/redis/srem/"

[[menu.main]]
	name = "STRLEN"
	weight = 232
	parent = "api-redis"
	url = "api/redis/strlen/"

[[menu.main]]
	name   = "Admin Reference"
	weight = 240
	url = "admin/"
	identifier = "admin"

[[menu.main]]
	name = "yb-ctl"
	weight = 241
	identifier = "yb-ctl"
	parent = "admin"
	url = "admin/yb-ctl/"

[[menu.main]]
	name = "yb-docker-ctl"
	weight = 242
	identifier = "yb-docker-ctl"
	parent = "admin"
	url = "admin/yb-docker-ctl/"

[[menu.main]]
	name = "yb-master"
	weight = 243
	identifier = "yb-master"
	parent = "admin"
	url = "admin/yb-master/"

[[menu.main]]
	name = "yb-tserver"
	weight = 244
	identifier = "yb-tserver"
	parent = "admin"
	url = "admin/yb-tserver/"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
